apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777 /data']
        volumeMounts:
        - name: flask-volume
          mountPath: /data
      containers:
      - name: flask-app
        image: aayushipatel/flaskapp:v0.2.2
        volumeMounts:
        - name: flask-volume
          mountPath: /data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
      volumes:
      - name: flask-volume
        persistentVolumeClaim:
          claimName: flask-pvc
